### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sdwfrost** [sempwn/LF-model#2]
Hi @sempwn, I see that the source for the Javascript version of TRANSFIL is under University of Warwick, while TRANSFIL2 has an MIT license in the main branch, but is otherwise unaltered in the gh-pages branch. Can you clarify the licensing on this repository?

**Comment by sempwn** [comment]
Added MIT license to this repository.

**Comment by sdwfrost** [comment]
Thanks! Much appreciated.
